Exam 2
toshkasob/2019-2-Track-Frontend-A-Sobenin pull request #15
Opened 2020-05-15 22:28 UTC by toshkasob

# Экзамен №2
Прошу  @martinkomitsky, @chexex или  @priver проверить его.
Что было сделано:
- 

- [x] В корневой папке проекта создать базовое приложение `exam_2` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) по инструкции выше

- [x] Использовать `TypeScript`
- [x] Сверстать страницу и необходимые компоненты. Использовать стили
- [?] Перевод с одного языка на другой (будет бонусом, если будет можно выбрать язык из выпадающего списка)
- [x] Перевод с неизвестного языка (автоопределитель из `API`)
- [ ] Manifest для `PWA` для `Splash screen` на мобильном устройстве [статья](https://medium.com/@applification/progressive-web-app-splash-screens-80340b45d210)
- [ ] Обернуть приложение в `docker` (чтобы запускалось локально в нем)
- [?] Задеплоить в решение `Travis CI`.
- [ ] Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи (выполняется лично с преподавателем)
- [ ] Ревью: получить правки по коду и исправить их (получается лично у преподавателя и выполняется самостоятельно)

2020-05-15 22:41 UTC, toshkasob commented
C travis попробую разобраться днем. 
Не понятно, почему возникает ошибка no-undef для всех YAtranslate/translate.ts (копировал из ДЗ6), возможно что тоже нужно сменить расширения ts на tsx, т.к. он подтягивает js из ДЗ6, которые были созданы с другими настройками, отличными от автоматически созданных при CRA

2020-05-18 07:37 UTC, martinkomitsky commented on exam_2/src/components/InputBox.tsx
> +			{/* <span class='placeholder'></span> */}
Вычистить закомментированный код из всего проекта

2020-05-18 07:42 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	const [chosenLangFull, setChosenLangFull] = useState('English');
вот этот state – это всего лишь стейт с предыдущей строки, но в полном виде. Предлагаю сделать объект, в котором будет расшифровка каждого короткого кода, типа:
```
const fullLangs = {
  en: 'English',
  ru: 'Russian',
  ...
};
```

и когда ты выводишь значение на 113 строке - делать это через `fullLangs[chosenLang]`, используя 1 стейт

2020-05-18 07:43 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +		props.handleLetLang(langFromList);
во всех компонентах, где используются данные из `props` лучше делать в первой строке компонента так:

```
const { prop1, prop2, prop3 } = props;
```

2020-05-18 07:43 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	let buttonOpenLangs: any = <button></button>;
почему any?

2020-05-18 07:43 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	let langBoxStyle: any;
почему any?

2020-05-18 07:44 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	useEffect(() => {
Этот эффект будет работать на каждый рендер компонента. Это так задумано?

2020-05-18 07:45 UTC, martinkomitsky requested changes
Исправить замечания + выполнить задание про PWA

2020-05-18 07:57 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +	useEffect(() => {
Да, так задумано, но название функции неверно отражает суть, т.к. происходит изменение значений кнопок после выбора языка. 
P.S. хотел также скрывать AutoDetect если выбран он, но забил на это =)

2020-05-18 07:58 UTC, toshkasob commented on exam_2/src/components/InputBox.tsx
> +			{/* <span class='placeholder'></span> */}
Done

2020-05-18 08:12 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +	const [chosenLangFull, setChosenLangFull] = useState('English');
по сути у меня выставляется значение fullLang по Lang, исходя из жесткой связки языков, находящейся в  {langsCode} from '../constants/AllLangs'; 
а эти стейты ввел, когда понял, что неверно выбрал ключ в '../constants/AllLangs'; , т.е. возможно стоит просто поменять местами fullLang  и cutLang в файле '../constants/AllLangs'; ?

2020-05-18 08:17 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +		props.handleLetLang(langFromList);
почему? 
удобнее же видеть, что есть в props при доступе через '.' и добавлять по ходу пьессы, если это потребовалось

> во всех компонентах, где используются данные из `props` лучше делать в первой строке компонента так:
> 
> ```
> const { prop1, prop2, prop3 } = props;
> ```

2020-05-18 11:47 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +	let buttonOpenLangs: any = <button></button>;
Done

2020-05-18 11:47 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +	let langBoxStyle: any;
Done

2020-05-18 18:36 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +	const [chosenLangFull, setChosenLangFull] = useState('English');
> вот этот state – это всего лишь стейт с предыдущей строки, но в полном виде. Предлагаю сделать объект, в котором будет расшифровка каждого короткого кода, типа:
> 
> ```
> const fullLangs = {
>   en: 'English',
>   ru: 'Russian',
>   ...
> };
> ```
> 
> и когда ты выводишь значение на 113 строке - делать это через `fullLangs[chosenLang]`, используя 1 стейт

так не получалось, если импортировать список языков, но сделал аналогично, поменяв в map'e местами ключ и значение

2020-05-18 19:13 UTC, toshkasob commented
> Исправить замечания + выполнить задание про PWA

Done

2020-05-19 07:29 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	const [chosenLangFull, setChosenLangFull] = useState('English');
там же написано, что "типа") не я пишу код за тебя, а ты 😁

2020-05-19 07:32 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +		props.handleLetLang(langFromList);
это старый стиль, а по новому стилю, который уже не новый, на самом деле, пишут так, чтобы сократить количество повторяющегося кода. Просто вытаскивают все, что надо, а дальше этим пользуются. TS тебе подскажет, если чего-то нет, так что насчет этого можно не бояться:

>
удобнее же видеть, что есть в props при доступе через '.'

2020-05-19 07:32 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +	useEffect(() => {
круто

2020-05-19 07:35 UTC, martinkomitsky commented on exam_2/src/components/Language.tsx
> +		}
как насчет этого?
```suggestion
	setShowLangs(!showLangs);
```

2020-05-19 07:36 UTC, martinkomitsky approved these changes
18

2020-05-19 07:37 UTC, merged

2020-05-19 07:39 UTC, toshkasob commented on exam_2/src/components/Language.tsx
> +		}
По привычке писал развернуто, но согласен, краткий вариант выглядит лучше